package com.example.sipinjam.utils

object UiMessageKey {
    const val GENERAL = "error_general"
    const val INVALID_ITEM_ID = "error_invalid_item_id"
    const val INVALID_BORROWING_ID = "error_invalid_borrowing_id"
    const val ITEM_NOT_FOUND = "error_item_not_found"
    const val ITEM_NOT_FOUND_OR_FAILED = "error_item_not_found_or_failed"
    const val BORROWING_NOT_FOUND = "error_borrowing_not_found"
    const val RETURN_NOT_FOUND = "error_return_not_found"
    const val RETURN_INVALID = "error_return_invalid"
    const val RETURN_ALREADY_PROCESSED = "error_return_already_processed"
    const val USER_NOT_FOUND_LOGIN_AGAIN = "error_user_not_found_login_again"
    const val USER_NOT_FOUND = "error_user_not_found"
    const val USER_NOT_LOGGED_IN = "error_user_not_logged_in"
    const val UID_NOT_FOUND = "error_uid_not_found"
    const val FIRESTORE_USER_NOT_FOUND = "error_firestore_user_not_found"
    const val BORROW_DATE_REQUIRED = "error_borrow_date_required"
    const val RETURN_DATE_REQUIRED = "error_return_date_required"
    const val BORROW_REASON_REQUIRED = "error_borrow_reason_required"
    const val DATE_FORMAT_INVALID = "error_date_format_invalid"
    const val BORROW_DATE_PAST = "error_borrow_date_past"
    const val RETURN_DATE_BEFORE_BORROW_DATE = "error_return_date_before_borrow_date"
    const val ITEM_UNAVAILABLE_OR_OUT_OF_STOCK = "error_item_unavailable_or_out_of_stock"
    const val ITEM_OUT_OF_STOCK = "error_item_out_of_stock"
    const val MAX_BORROW_DURATION = "error_max_borrow_duration"
    const val SEND_BORROW_REQUEST_FAILED = "error_send_borrow_request_failed"
    const val LOAD_CATALOG_FAILED = "error_load_catalog_failed"
    const val LOAD_FAVORITES_FAILED = "error_load_favorites_failed"
    const val LOAD_HISTORY_FAILED = "error_load_history_failed"
    const val LOAD_ITEMS_FAILED = "error_load_items_failed"
    const val LOAD_BORROWINGS_FAILED = "error_load_borrowings_failed"
    const val LOAD_RETURNS_FAILED = "error_load_returns_failed"
    const val LOAD_BORROWING_DETAIL_FAILED = "error_load_borrowing_detail_failed"
    const val ADD_ITEM_FAILED = "error_add_item_failed"
    const val EDIT_ITEM_FAILED = "error_edit_item_failed"
    const val DELETE_ITEM_FAILED = "error_delete_item_failed"
    const val UPLOAD_PHOTO_FAILED = "error_upload_photo"
    const val SUBMIT_RETURN_FAILED = "error_submit_return_failed"
    const val REJECT_RETURN_FAILED = "error_reject_return_failed"
    const val RETURN_CONDITION_REQUIRED = "error_return_condition_required"
    const val ADMIN_NOTE_REQUIRED_REJECT_RETURN = "error_admin_note_required_reject_return"
    const val EMPTY_NAME = "error_empty_name"
    const val EMPTY_EMAIL_PASSWORD = "error_empty_email_password"
    const val EMPTY_FULL_NAME = "error_empty_full_name"
    const val EMPTY_EMAIL = "error_empty_email"
    const val PASSWORD_MIN_6 = "error_password_min_6"
    const val CURRENT_PASSWORD_REQUIRED = "error_current_password_required"
    const val NEW_PASSWORD_MIN_8 = "error_new_password_min_8"
    const val PASSWORD_CONFIRMATION_MISMATCH = "error_password_confirmation_mismatch"
    const val SAVE_PROFILE_FAILED = "error_save_profile_failed"
    const val URL_NOT_FOUND = "error_url_not_found"
    const val LOAD_HOLIDAY_INFO_FAILED = "error_load_holiday_info_failed"
    const val LOAD_HOLIDAY_CACHE_FAILED = "error_load_holiday_cache_failed"
    const val LOAD_ITEM_FAILED = "error_load_item_failed"
    const val CHANGE_PASSWORD_FAILED = "error_change_password_failed"
    const val VERIFY_RETURN_FAILED = "error_verify_return_failed"
    const val APPROVE_BORROWING_FAILED = "error_approve_borrowing_failed"
    const val REJECT_BORROWING_FAILED = "error_reject_borrowing_failed"
    const val TRY_AGAIN = "error_try_again"
    const val EMAIL_NOT_REGISTERED = "error_email_not_registered"
    const val WRONG_PASSWORD = "error_wrong_password"
    const val CURRENT_PASSWORD_WRONG = "error_current_password_wrong"
    const val INVALID_EMAIL_FORMAT = "error_invalid_email_format"
    const val TOO_MANY_ATTEMPTS = "error_too_many_attempts"
    const val NO_INTERNET = "error_no_internet"
    const val LOGIN_FAILED = "error_login_failed"
    const val EMAIL_ALREADY_REGISTERED = "error_email_already_registered"
    const val REGISTER_FAILED = "error_register_failed"
    const val SUCCESS_PROFILE_SAVED = "success_profile_saved"

    fun maxBorrowDuration(maxDays: Int): String = "$MAX_BORROW_DURATION|$maxDays"

    fun uploadPhotoFailed(detail: String? = null): String = "$UPLOAD_PHOTO_FAILED|${detail.orEmpty()}"
}
